### ISSUE TITLE
Changing the the tilt of the Roundabout

### ISSUE THREAD

**Issue by Oliblanton** [fredleblanc/roundabout#11]
My roundabout looks tilted upward. How do I make all the images horizontally aligned?

http://rejuveniix.com/HomeBanner/

**Comment by fredleblanc** [comment]
Tilt can be set as an option. There is a [lesson](http://fredhq.com/projects/roundabout#/learn) on how to set options. 

Tilt is more of an art than a science, and differs from shape to shape. That said, it will be a matter of playing with it to get something that looks right.

Closing this issue as it's not an issue with Roundabout itself, but a question on a specific implementation.

**Comment by Oliblanton** [comment]
Thanks for your response. How would I make my roundabout look like this one you have used on the roundabout page that doesn't seem to tilt at all. http://cl.ly/E86v

Thanks for your help!

**Comment by fredleblanc** [comment]
Here are the options that I used in that one:

``` javascript
$("#sample-roundabout").roundabout({
    tilt: 0.6,
    minScale: 0.6,
    minOpacity: 1,
    duration: 400,
    easing: 'easeOutQuad',
    enableDrag: true,
    dropEasing: 'easeOutBounce'
}, function() {
    $(this).fadeTo(500, 1);
});
```

Note that I'm using an easing function from the jQuery easing plugin, and enabling drag and drop with the drag and drop plugins that are separate from Roundabout itself. I also have the Roundabout set to be an opacity of 0 until it's made, and it then fades in from there.

**Comment by Oliblanton** [comment]
Perfect! Very cool. Thanks for your time.
