### ISSUE TITLE
Autoplay start timing offset?

### ISSUE THREAD

**Issue by mxmilkiib** [fredleblanc/roundabout#12]
Is there some method one could use to offset the start of autoplay of roundabouts in differing ids?

**Comment by fredleblanc** [comment]
There isn't at the moment, but it seems like that's something that could be useful. I'll look into it this week.

**Comment by fredleblanc** [comment]
OK I lied, it was an easier implementation than I was thinking, so it's in the all new [v2.3](https://github.com/fredhq/roundabout/zipball/v2.3). How to use it:

``` javascript
$("ul#roundabout").roundabout({
    autoplay: true,
    autoplayInitialDelay: 2000
});
```

This will delay for 2000 milliseconds (2 seconds) and then start autoplay. This delay **only works for the initial autoplay start**, other autoplays can be delayed by being put into a setTimeout in JavaScript. (The initial one could have been put into a setTimeout itself, and in fact that's all that's happening here, but it seemed useful enough that it should be built in with an option.)

Also, the setTimeout call internally is being stored in Roundabout's data object, and can be cleared like so:

``` javascript
clearTimeout($("ul#roundabout").data("autoplayStartTimeout"));
```

**Comment by mxmilkiib** [comment]
Fab, many thanks!
