### ISSUE TITLE
Mousewheel Support / getChildInFocus

### ISSUE THREAD

**Issue by ghost** [fredleblanc/roundabout#13]
Hi,

at the moment I using the mousewheel plugin from brandon aaron.
it is not as smooth as the drag drop extension but with the duration set to low values every fired event will be processed, yay.

the problem is that sometimes getChildInFocus returns false.
usually when the (bearing?) current position is 180° or 0°

can you give me a hint what im doing wrong?

best regards,
simon

the code i use

``` javascript
$('.coverflow').bind('mousewheel',function(e,delta,deltaX,deltaY){

                var cPos, nextPos;

                e.preventDefault();
                e.stopPropagation();

                cPos = $('.coverflow').roundabout("getChildInFocus");
                nextPos = cPos+delta;

                if(nextPos > 15 ) nextPos = nextPos-16;
                if(nextPos <  0 ) nextPos = nextPos+16;

                console.log("d:"+delta+" nextPos:"+nextPos+" cPos:"+cPos +" childCount:" +childCount);
                console.log(delta, deltaX, deltaY);

                $('.coverflow').roundabout("animateToChild", nextPos, 33);
            });

```

how i setup 

``` javascript
$('.coverflow').roundabout({
                childSelector: ".coverflow_element",
                startingChild: <%=startingCover%>,
                autoplay: true,
                autoplayInitialDelay: 2500,
                autoplayDuration: 2500,
                autoplayPauseOnHover: true,
                enableDrag: true,
                dropEasing: "swing",
                responsive: false,
                clickToFocus: true,
                tilt: 0.0,
                minOpacity: 0.1,
                maxOpacity: 1.0,
                minScale: 0.1,
                maxScale: 1.0,
                shape: 'squareshrink',
                triggerFocusEvents: true

            })
```

there are 16 elements in the flow.

Mousewheel Examples:
http://flowplayer.org/tools/toolbox/mousewheel.html
https://github.com/brandonaaron/jquery-mousewheel

**Comment by fredleblanc** [comment]
I think the reason that drag and drop works smoother is that it's taking a different approach (and has one other advantage). Your code is using each mouse-wheel movement to move to the next child, drag and drop is taking the distance traveled and manually changing the bearing accordingly. The second half of that is where drag and drop has the advantage, which is that "drop" is an action people take. At that point I can find the nearest child and animate to that. With the mouse-wheel, it's hard to know people's intentions.

To best guess people's intentions, I'd probably set things up with a setTimeout. Each mouse-wheel movement should clear any previous ones and start a new one. Then, after some duration of no mouse-wheel movement, have it animate to the nearest child. For each of the mouse-wheel movements themselves, you could probably use `adjustBearing.`

The rest of your set up looks correct. (Looks like you're using a custom-created shape, I'd be interested to see what it looks like.)

**Comment by ghost** [comment]
thanks for the fast response!

adjustBearing kinda messes up the next clicks to focus new items.
`$('.coverflow').roundabout("adjustBearing", 360/childCount*delta);`

am i right with the assumption that bearing is the offset and focusBearing the origin?

went back to `animateToNext/PrevChild` with a duration of 10. works perfect and reflects the scrolling speed quite good and no more false returns from getChildInFocus :-)

funny thing is in Chrome the mouse delta is always -1 or 1 but gets fired more often while in FF the max. Delta goes to +/- 3

the shape is nothing fancy and not done by now. at the moment the only difference to square shape is y gets always set to zero.
at the end i want to rebuild the ImageFlow (http://finnrudolph.de/ImageFlow/Examples#Enable_circular_mode Example 3) behaviour as seen by http://www.you-fm.de/ (scroll down) but with the images aligned to the bottom. and smaller scales on the outside. if the shape is done i will share it.

best regards,
simon

**Comment by fredleblanc** [comment]
I've always found that different browsers return the speeds in different ways, so yeah, you might need to adjust per browser.
