### ISSUE TITLE
Stopping immediately

### ISSUE THREAD

**Issue by stefanmeschke** [fredleblanc/roundabout#135]
Hi,

is it possible to stop the roundabout animation immediately?
Now it animates to the nearest child and stops then.

I hope anyone could help me? Thanks!

**Comment by tonimoeckel** [comment]
We just found a dirty hack - setting the data property "stopAnimation". Do this to stop the autoplay animation immediately:

$('ul.carousel-navigation').data("roundabout").stopAnimation = true;
$('ul.carousel-navigation').roundabout('stopAutoplay', false);

But I think a public method would provide a better api. We are happy to fork it ;)

**Comment by stefanmeschke** [comment]
+1
