### ISSUE TITLE
Vertical drag/drop doesn't work

### ISSUE THREAD

**Issue by danjordan** [fredleblanc/roundabout#14]
Example...

https://gist.github.com/1869930

If you uncomment line 15 the roundabout only responds to horizontal dragging and not vertical dragging.

**Comment by fredleblanc** [comment]
Please check out the `dragAxis` option: http://fredhq.com/projects/roundabout#/dragAxis — switch this to 'y' and it'll do what you're looking for.

(Aside: awesome issue post. Made it super easy to get you an answer.)

**Comment by danjordan** [comment]
Cheers for the quick response! I expected it to be something that was already built in, but wasn't sure where the best place to post the question was!

It works super now :D
