### ISSUE TITLE
Ability to control the offset of non focused elements.

### ISSUE THREAD

**Issue by fleeting** [fredleblanc/roundabout#15]
Is there a way to control how much of the non-focused elements are visible from the in-focus element? Basically I have four panels in roundabout but want only a small portion of the next/prev elements to be visible from behind the in-focus.  Maybe a way to say an offset of show only 25px of the non focused blocks that would adjust the position left accordingly?

**Comment by fredleblanc** [comment]
You can alter this by setting the width on the element upon which you're calling Roundabout. The wider, the further apart they'll look.
