### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by ghost** [fredleblanc/roundabout#16]
I configured roundabout according to the tutorial http://fredhq.com/projects/roundabout#enable-drag-drop

I am using the following scripts:

jquery.js 1.4.4
jquery.roundabout.min.js 2.3
jquery.event.drag-2.0.min.js
jquery.event.drop-2.0.min.js

When clicking on a roundabout item my firebug console displays the javascript error:

a.setAttribute is not a function (jquery.js line 56)

**Comment by fredleblanc** [comment]
Can you post a sample page where you have this working? (Or, you know, not working.)
