### ISSUE TITLE
Mouswheel

### ISSUE THREAD

**Issue by ghost** [fredleblanc/roundabout#17]
Im working on a basic mousewheel support for my roundabout.

I am using:
jquery.mousewheel.js 3.0.6 http://brandonaaron.net/code/mousewheel/docs
jquery.roundabout.js 2.3

My first working example looks like this:

<pre>
instance.roundabout(settings.roundabout);

instance.bind('mousewheel', function(event, delta) {
  event.preventDefault();

  if (delta > 0) {
    instance.roundabout('animateToNextChild', 1, 'linear');
  }
  else {
    instance.roundabout('animateToPreviousChild', 1, 'linear');
  }
});
</pre>

Now I am trying to create a circular animation on mousewheel movements like:
http://finnrudolph.de/ImageFlow/Examples#Enable_circular_mode
http://www.professorcloud.com/mainsite/carousel.htm

I read your comment on https://github.com/fredhq/roundabout/issues/13#issuecomment-4054073 and made some attempts with animateToDelta and animateToNearestChild but nothing worked like intended.

Could you please give me an example of how to create a circular animation with easing in response to mousewheel movements.

Thanks in advance and best regards.

**Comment by fredleblanc** [comment]
There are methods that you can call to create very specific animation easing in whichever way that you'd like (for example, `setBearing` and a bunch of math that calls that each time). This combined with a mousewheel-plugin should get you where you want to go — on each mousewheel event, update the math of your moving Roundabout and do another animation with a `setBearing` at each step.

Circular animation with easing as tied to a mousewheel is out of scope for this project. Someone could write a wrapper function around Roundabout that did this, but that's not something for me.
