### ISSUE TITLE
Grayscale (inactive)

### ISSUE THREAD

**Issue by synergies** [fredleblanc/roundabout#19]
Is it possible to setup grayscale option (along with opacity) for the inactive items?

**Comment by synergies** [comment]
bump

**Comment by fredleblanc** [comment]
Opacity works because it is a supported CSS property that jQuery can animate. You may be able to get away with this by doing a tricky image-fade-replacement, but it isn't (and won't) be built into Roundabout.

**Comment by synergies** [comment]
Thanks for the reply Fred!  I was able to get it working by doing a "tricky
image-fade-replacement" -  http://annualreport.cbre.com/

On Thu, May 31, 2012 at 3:01 PM, Fred LeBlanc <
reply@reply.github.com
