### ISSUE TITLE
Option for  not applying it if there are less than n items

### ISSUE THREAD

**Issue by stephaneeybert** [fredleblanc/roundabout#20]
Say there are only 2 items, applying the roundabout on these two sort of hides one behind the other. One such example can be seen at my website :-) at 
http://www.learnintouch.com/elearning/exercise/69/page/221/subscription/

It would be handy to tell roundabout, start rounding only if there are more than, say, 4 items.

Other than that, what an awesome plugin !

**Comment by fredleblanc** [comment]
This would be better handled by an if statement surrounding the Roundabout initialization.

**Comment by stephaneeybert** [comment]
I just did that :-) Thanks Fred.
