### ISSUE TITLE
A roundabout of infinite diameter

### ISSUE THREAD

**Issue by stephaneeybert** [fredleblanc/roundabout#21]
It'd be nice to have an infinite diameter to the roundabout, or even better, a diameter that could be scaled, so as to have a wheel that looks like a scrolling banner, or almost. This way, some of the items would be out of the view, and not playing hide and seek from behind.

**Comment by fredleblanc** [comment]
The width can of the holding element can be made wider, spreading items out. I suppose on a large-enough scale it might accomplish this. What you're describing is something that other plugins (usually they call themselves "carousel" plugins, although I think that name is a bit weird) do, not what Roundabout is made to do.

Probably something like [jCarouselLite](http://www.gmarwaha.com/jquery/jcarousellite/) is what you want.

**Comment by stephaneeybert** [comment]
Thanks for the tip !

Stephane

---

 De: Fred LeBlanc reply@reply.github.com
: Stephane Eybert mittiprovence@yahoo.se 
Envoy le : Samedi 24 mars 2012 18h52
Objet: Re: [roundabout] A roundabout of infinite diameter (#21)

The width can of the holding element can be made wider, spreading items out. I suppose on a large-enough scale it might accomplish this. What you're describing is something that other plugins (usually they call themselves "carousel" plugins, although I think that name is a bit weird) do, not what Roundabout is made to do.

Probably something like [jCarouselLite](http://www.gmarwaha.com/jquery/jcarousellite/) is what you want.

---
