### ISSUE TITLE
Cannot render the easing and bounce effects.

### ISSUE THREAD

**Issue by stephaneeybert** [fredleblanc/roundabout#22]
I was looking for a forum so as to post my issue at rendering the easing and bounce effects.

It can be seen at http://www.learnintouch.com/elearning/exercise/55/page/194/

Is there any forum somewhere ?

Cheers,

**Comment by stephaneeybert** [comment]
I noticed the easing and bouncing effects work fine on my iPod Touch os 4.3.5.

But they do not work on my Firefox 10.0.2 on Linux Mint 12.

And neither on 17.0.963.56 (Developer Build 121963 Linux) Built on Ubuntu 11.10, running on LinuxMint 12.

**Comment by fredleblanc** [comment]
That page is not found. Were you setting the easing for the Roundabout?

**Comment by stephaneeybert** [comment]
Sorry Fred, here is the correct url

http://www.learnintouch.com/elearning/exercise/55/page/194/subscription/

Otherwise I'm also fighting a bit to have a width below the roundabout, it oversteps on my page title..

Kind Regards,

Stephane

**Comment by fredleblanc** [comment]
Sorry, just getting to this now. It seems Roundabout is gone from this page.

**Comment by stephaneeybert** [comment]
Hello Fred,

Yes, I had to go for another solution as the roundabout was not exactly what I was looking for.

So I removed it, that was some time ago :-)

I just found, today in fact, another solution, the slider plugin, which answers my needs quite nicely.

Thanks again for the support.

Kind Regards,

Stephane
