### ISSUE TITLE
Disconnect between the visible scroll and the memory of it 

### ISSUE THREAD

**Issue by stephaneeybert** [fredleblanc/roundabout#23]
There is a disconnect between the scroll and the memory the roundabout has of it.

Say I scroll a bit from the far right hand side, and then point to this same far right hand side and click, when I barely start to drag then the roundabout is doing a sort of reset, to the position it has in its own memory.

This happens on my Firefox 10.0.2 on Linux Mint 12 and on Chrome 17.0.963.56 (Developer Build 121963 Linux) Built on Ubuntu 11.10, running on LinuxMint 12 but does NOT happen on my iPod Touch os 4.3.5.

**Comment by stephaneeybert** [comment]
This can be seen at http://www.learnintouch.com/elearning/exercise/55/page/191

**Comment by stephaneeybert** [comment]
It seems the scroll index is reset on each scroll.

**Comment by fredleblanc** [comment]
This page is not found.
