### ISSUE TITLE
Animation Broken in jQuery v1.7.2

### ISSUE THREAD

**Issue by fredleblanc** [fredleblanc/roundabout#24]
Roundabout doesn't seem to animate anymore when used with jQuery v1.7.2. Need to look into this, but I'm a bit busy at the moment. Use with v1.7.1 for now.

**Comment by czj** [comment]
I still have a problem : animation runs very fast and goes around something like 10 times before stopping on the clicked item. Reverting to jQuery 1.7.1 fixes it :-(

**Comment by asp24** [comment]
I found the same issuie with jquery 1.7.2 and jquery.effects.core (from jquery UI) enabled

**Comment by Timidfriendly** [comment]
I can confirm that the animation doesn't work in jquery 1.8.3 or 1.9.1

Is there a fix for this?
