### ISSUE TITLE
Callbacks "animationStart" and "animationEnd" don't work (Jquery 1.7.2)

### ISSUE THREAD

**Issue by ricardofiorani** [fredleblanc/roundabout#28]
The callbaks for the "animationStart" and "animationEnd" events don't work properly after each "turn" animation.

I'm trying both ways:

declaring the function right in the callback property:

ex: 

```
$('seletor').roundabout({
    animationStart:function (){
          //do something
   }
});
```

and declaring the function name to call it, ex:

```
$('seletor').roundabout({
    animationStart: function_to_be_called()
});
```

**Comment by jpgcode** [comment]
This is not working for me either! Someone knows how to fix?

**Comment by Lythimus** [comment]
Similar problem but with autoStart.

**Comment by Lythimus** [comment]
The issue for startAutoplay is that it is not the correct parameter name. If you check the source of 2.4 the correct title is autoplayCallback. I have no tried animationStart or animationStop, but in the source they are actually stopAnimation and I believe allowAnimation. PLEASE update the documentation.

**Comment by fredleblanc** [comment]
[`animationStart`](http://fredhq.com/projects/roundabout#/animationStart) and [`animationEnd`](http://fredhq.com/projects/roundabout#/animationEnd) are _events_ that you can listen for, not callback functions that you can add to the list of options. (Note that in the documentation, they're in a section called _[Hookable Events](http://fredhq.com/projects/roundabout#/events)_.)

Both of these events can be heard like so:

``` javascript
$('#roundabout')
    .bind('animationStart', function() {
        // do something
    })
    .bind('animationEnd', function() {
        // do something else
    });
```

Also, [`autoplayStart`](http://fredhq.com/projects/roundabout#/autoplayStart) is another event that can be listened for in the same way as the example above. [`startAutoplay`](http://fredhq.com/projects/roundabout#/startAutoplay), however, is method that will tell Roundabout to start autoplaying if it isn't already doing so. This can be called like so:

``` javascript
$('#roundabout')
    .roundabout("startAutoplay");
```

Finally, there's an optional _callback_ parameter that you can pass into `startAutoplay` that will be called each time an animation completes (as a result of the autoplay), this can be done like so:

``` javascript
$('#roundabout')
    .roundabout("startAutoplay", function() {
        // do something
    });
```
