### ISSUE TITLE
Roundabout conflicts with Easing.1.3.js

### ISSUE THREAD

**Issue by ricardofiorani** [fredleblanc/roundabout#29]
When declaring easing 1.3 the roundabout plugin acts kinda weird. it rotates a lot more times than it should normally.

**Comment by travhimself** [comment]
Confirmed here. The roundabout still moves to the correct frame, but it will appear to spin wildly in the process.

**Comment by czj** [comment]
Same thing here, but it only occurs when using jQuery 1.7.2.
jQuery 1.7.1 + easing 1.3 works properly.

**Comment by pickledlove** [comment]
Same thing here, did anyone find a solution?

**Comment by bjyd** [comment]
Hi, same problem here.
I tried "jQuery1.7.1 + easing1.3" but it doesn't work with Roundabout 2.4

**Comment by fredleblanc** [comment]
Sorry, need to find some time to investigate this.

**Comment by jadams01** [comment]
I'm looking into this as I want to update my jQuery to 1.7.2 but love this plugin.
Would be good to branch this repo to work on over the weekend. Hopefully have an answer for you by then.

**Comment by jmartsch** [comment]
Same here with Firefox 12 and Chrome 19. Seems to be a problem with jQuery 1.7.2.
1.7.1 works fine

**Comment by gpetrov** [comment]
This issue is becoming really annoying as we can't use the latest easing 1.3 plugin and the latest jquery 1.7.2
Please fix it asap ...

**Comment by smcx** [comment]
if you comment out the fix made for 1.7.2 beta, it seems to fix  the problem. Lines 692-694 of the jquery.roundabout.js

**Comment by snichini** [comment]
I've got the same issue with jquery UI 1.8.16 (at least)

edit : the sliding is acting pretty crazy, i've got a lot turn around for an item next to the current one.
I've tried to comment the patch of line 692-694, but didn't not fix the problem.

**Comment by fredleblanc** [comment]
Alright, this one is a bit weird. If you want to use `linear` easing and jQuery 1.7.2, you _cannot_ have jQuery easing included on your page. However, all other scenarios should work.

**Comment by DonDi1989** [comment]
Is there any solution, i have the same problem. Roundabout script is conflicting with jQuery UI 1.10.3 ?
