### ISSUE TITLE
jQuery 1.7.2 support

### ISSUE THREAD

**Issue by Lythimus** [fredleblanc/roundabout#31]
I was using the latest version of jQuery and when I clicked an element in the carousel it would loop completely around every time (rotating n+1 times where n is the number of elements in the carousel). Similar for auto rotate. I switched down to jQuery 1.4.4 and received expected click behavior (switches to the item clicked). I tested in both FF3.6 on OS 10.5 and also on Opera 11.62 on Windows 7.

**Comment by sheckyboy** [comment]
Same exact experience after upgrading.  Using Win7 and Chrome 18.

**Comment by jadams01** [comment]
I'm experiencing the same problem.
It happens in all browsers. Latest jQuery (1.7.2) changes the smooth transition to a crazy spin.
As pointed out by Lythimus it loops through the images before finally stopping on the correct image. It looks very messy.

Had a look in the source code and can't see anything obvious, likewise not obvious what it could be in jQuery itself.

**Comment by fredleblanc** [comment]
Something changed from 1.7.1 to 1.7.2 in the animation area. Can you confirm that you're using v2.4 of Roundabout?

**Comment by jadams01** [comment]
It's definitely v2.4 I'm using of roundabout.
I'm using 1.7.1 as a workaround but obviously this can't be the permenant solution.
Incidentally it's www.jasoft.co.uk that has the roundabout (Images at top of homepage).

Cheers,
Jack

**Comment by fredleblanc** [comment]
This seems to be related to the change in animation internals in jQuery 1.7.2, which I'm going to lump into issue [#29](https://github.com/fredhq/roundabout/issues/29). Closing this issue for now, need to find time to look into that one.
