### ISSUE TITLE
Reload/Cache Problem with Images in Firefox

### ISSUE THREAD

**Issue by MitchMikel** [fredleblanc/roundabout#32]
We love "Roundabaout", but we have following problem. You can see it at http://hochzeitsverzeichnis.agentur-mai.de. When you load the page you can see the "Roundabout-Slider". It works fine. But when you press CTRL+F5 in Firefox, the page reloads but the images a resized too small. When you press just F5, the images are resized correct.
What can we do? Is there a known solution? Thank you very much for answering.

**Comment by fredleblanc** [comment]
Looking in the browser, I do see any widths/heights set on your LI's. Maybe try giving them an initial size (set in em's)?

**Comment by MitchMikel** [comment]
Thanks, thanks, thanks. Giving initial sizes with "em" worked fine. You 
are the greates. My boss told me to use your plugin. Now I tell him to 
give a donation.
So far, i send you a piece of cake for your coffee/tea.
Here it is: ( >

Best regards
Mitch Mikel

Am 02.05.2012 15:26, schrieb Fred LeBlanc:

> Looking in the browser, I do see any widths/heights set on your LI's. Maybe try giving them an initial size (set in em's)?
> 
> On May 2, 2012, at 4:34 AM, MitchMikel wrote:
> 
> > We love "Roundabaout", but we have following problem. You can see it at http://hochzeitsverzeichnis.agentur-mai.de. When you load the page you can see the "Roundabout-Slider". It works fine. But when you press CTRL+F5 in Firefox, the page reloads but the images a resized too small. When you press just F5, the images are resized correct.
> > What can we do? Is there a known solution? Thank you very much for answering.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > ## https://github.com/fredhq/roundabout/issues/32
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/fredhq/roundabout/issues/32#issuecomment-5461266

## 

Mit freundlichen Grüßen
Michael Schmelzing

Agentur Mai
Inh:Axel Lauer
Karl Kunger Strasse 63
12435 Berlin
Fon: 030/ 53210040
Fax: 030/ 53210044

URL:
www.axellauer.de
www.agentur-mai.de (In Suchmaschinen On Top?)
www.kuenstleragentur-mai.de (Eventanreicherung?)

Steuer-Nummer 36/413/62824
Finanzamt Berlin/Treptow

**Comment by fredleblanc** [comment]
Ha, thank you.
