### ISSUE TITLE
Autoplay in IE

### ISSUE THREAD

**Issue by ryanperry** [fredleblanc/roundabout#33]
With autoplay enabled and when you scroll past the roundabout carousel on transition the page will jump up to the carousel on each slide change in IE.

**Comment by Bolamar** [comment]
i have same problem , any ideas to solve it
thanks in advance

**Comment by ryanperry** [comment]
I found that issue was due to using div instead of li. Oddly enough when I switched to li the jumping on slide transition was gone.

**Comment by fredleblanc** [comment]
This is due to Roundabout calling the `focus` event on an item as it moves to the "front" after an animation. To prevent this focus event from firing, set `triggerFocusEvents` to `false` in your options.

**Comment by Skytorn86** [comment]
Hi
I have an other problem with autoplay, when i stop it with a button preview at this effect, and i restart him, it turn very quickly, after on a second way, when i change the autoplayduration. I m french so my english it s a little poor. Sorry but, if you have a idea for that :). My best regards.
