### ISSUE TITLE
How can I hook to event 'animationStart' ?

### ISSUE THREAD

**Issue by beshur** [fredleblanc/roundabout#38]
Hello.

Thank you for the great script! It is really awesome.

In the Hookable Events section of the API there is an `animationStart` event.
But I was unable to hook anything to it in any way I know (bind(), $(selector).roundabout().animationStart() or setting it as option).

What is a secret?
Thank you.

**Comment by fredleblanc** [comment]
This event is called on the element that you've called Roundabout on. So, if you've targeted `ul.roundabout`, for example, you'll want to do:

``` javascript
$("ul.roundabout")
    .roundabout({
        // this is your initial roundabout call, with your options set however
    })
    .bind("animationStart", function() {
        // do something here
    });
```
