### ISSUE TITLE
Different dimensions for active item

### ISSUE THREAD

**Issue by jonathanstegall** [fredleblanc/roundabout#41]
I think it would be great if we could change the dimensions for the active item - .roundabout-in-focus. I tried doing this in CSS, but since the styles are inline this does not apply.

It could be an option, maybe? The use case I'm thinking of is one in which I have several items, but I want to display more content on the active one. Maybe an image shows in the inactive ones, and I show the image and a descriptive paragraph or two with the active one.

**Comment by fredleblanc** [comment]
You could use CSS's scale transform to accomplish this. This could also be done with events and some extra JavaScript. There are no plans to build this in.
