### ISSUE TITLE
Excessive roundabouting

### ISSUE THREAD

**Issue by willpower232** [fredleblanc/roundabout#42]
In using version 2.4 copied from the github repo with minimal options, as suggested by the lessons on the website page, the roundabout rotates several times before landing on the clicked element.

I switched to version 2.1.1 which was being used by the website and the problem went away, the roundabout behaved as normal and only rotated to the clicked element.

**Comment by norixx** [comment]
same problem here with 2.4. I also switched back to 2.1.

**Comment by fredleblanc** [comment]
This is due to jQuery.easing, and has hopefully been fixed in v2.4.2.
