### ISSUE TITLE
Issue with minScale and maxScale

### ISSUE THREAD

**Issue by allmon01** [fredleblanc/roundabout#5]
I haven't confirmed yet but I believe the issue exists with minOpacity, maxOpacity, minZ, and maxZ as well.

Javascript error in Firefox 8.0 is as follows:
(info.scale.min + info.scale.diff \* factors.scale).toFixed is not a function on line 1088

I fixed this by using the parseFloat function.
factors.adjustedScale = parseFloat((info.scale.min + (info.scale.diff \* factors.scale))).toFixed(4);

Thanks for getting back to me on the autoplay issue I had. Great Plugin btw!

**Comment by fredleblanc** [comment]
I can't seem to recreate this issue. I've tried all sorts of integers and floats as min and max values and am not receiving any errors (in any Firefox, I've checked versions 3.6 – 10, which as of now is the current version).
