### ISSUE TITLE
Focused item(top object) delay

### ISSUE THREAD

**Issue by norixx** [fredleblanc/roundabout#50]
Hi.
I am experiencing a tiny issue.
The problem is that top layer item always bit comes in delayed ( let's say 100ms?).

i would like to know how to fix that.

example: http://jsfiddle.net/nori2tae/f5CjK/
- roundAbout ver. 2.1 (2.4 circular motion went crazy by the way. It is like adding 1 extra rotation when i press next/prev button)
- jquery: 1.7.2
- jquery easing: enabled

**Comment by fredleblanc** [comment]
The delay is most likely due to the animation easing that you're using. Try a different one, like `easeOutQuad` and everything seems to look normal to me. As for the circular motion thing, I _just_ pushed something that should fix that.
