### ISSUE TITLE
Items disappearing in Safari

### ISSUE THREAD

**Issue by alonsodiaz82** [fredleblanc/roundabout#52]
Hi!

Thank you for a great project!

I don't know if you already addressing this bug, I just found in Safari (regardless of operating system), but in case you aren't, here it is.

When you (in this example) wait for the animation to autoplay or click next, the items begin to disappear. Once all the items have been viewed, the last 2 or 3 items are all that remains visible. All other items are gone.

Example:
http://jsfiddle.net/f5CjK/38/

Best regards,
Alonso Diaz

**Comment by fredleblanc** [comment]
In your example, you have `maxScale` set to -1. Not sure why, may have just been a typo. Remove that and things work normally for me. Also, for best image use, define the height and width of your `li`s in CSS in em's so that they're the size of the images they contain. Then set the width of `li img` to be 100%.

**Comment by alonsodiaz82** [comment]
Thanks! I'll try that :)

**Comment by alonsodiaz82** [comment]
It worked!

I had different object that I put in to the roundabout function as argument to test and debug. I was testing all of them at same time to see witch one worked.

Note to self: use EM in roundabout! :) and no -1 in maxScale :)

Thanks again!

**Comment by fredleblanc** [comment]
You're welcome! Thanks for providing an example. Made everything a whole lot easier.

**Comment by alonsodiaz82** [comment]
How do you make the items on the side of the focused item appear smaller? I just can't get that to work. Does it have to do with the width or maybe the shape (using square and default).

What I mean is the 3D perspective look that you have in your demo. I've tried doing just that, but I can't get it to work.
http://fredhq.com/projects/roundabout/demos/standard

Best regards,
Alonso Diaz

**Comment by fredleblanc** [comment]
Make sure that your minScale is smaller than your maxScale (which it is by default), and use ems. As things move, Roundabout changes the font-size for each box accordingly. Sizing things in ems (or the `li` in ems, the images inside to be width 100%) will make things shrink with it.

**Comment by alonsodiaz82** [comment]
Thank you! I'll have a go at it.

Result after what Fred speaks about in this comment:
http://jsfiddle.net/f5CjK/39/
