### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by nickff** [fredleblanc/roundabout#53]
It would be amazing to be able to add bullets below a roundabout for jumping to different items in the carousel (pagination).

Any thoughts on whether this is possible now or would require major work would be awesome!

**Comment by fredleblanc** [comment]
This is possible now, although it's not automated for you. You can tell Roundabout to animated to a given moving item like so:

``` javascript
// animate to the second item (roundabout is 0-based)
$("ul").roundabout("animateToChild", 1);
```

So make your list, create your links, and then bind that code above to their click events. You can use your own trickery to make things more dynamic, such as using `$.each()`'s index iterator to choose the child to animate to.
