### ISSUE TITLE
Show only 3 images out of many dozens

### ISSUE THREAD

**Issue by ciso** [fredleblanc/roundabout#57]
Hi,

first of all: You did a really great job! Your plugin is awesome!
I have many products (they grow dynamically, but there are at least about 20) and would like to show only 3 out of them.
For example: 5 Products:
A - B - C - D - E

When the user enters the Page and the roundabout is centered the user will be displayed:
B - C - D

Then, when he clicks 'next', he will be displayed:
C - D - E

I have checked the settings of your roundabout but didn't find an attribute to specify this.
Is there a way to achieve this? Thanks in advance!

**Comment by fredleblanc** [comment]
The way to have 3 things show up in front with the default shape is to only have 5 or 6 things in your Roundabout. You could also attempt to write a custom shape, but that's a lot easier said than done.
