### ISSUE TITLE
Center Smaller Images

### ISSUE THREAD

**Issue by mouse0270** [fredleblanc/roundabout#8]
Is it possible to center an image that is in focus?

So if I have a carousel that has numerous photos of different sizes, the one in focus well vertically center instead of being aligned with the tilt?

**Comment by fredleblanc** [comment]
This is something that would be done with CSS outside of Roundabout. If you're using Roundabout with an unordered list, for example, you would need to come up with CSS to center images within the list-items as it moves. (You could also do this with a combination of JavaScript, hooking into one or more of Roundabout's events.)
