### ISSUE TITLE
Images don't scale

### ISSUE THREAD

**Issue by tonye** [fredleblanc/roundabout#84]
It seems Roundabout doesn't shrink images contained in the elements that are shrinking, which pushes content right outside the bounds of the element when it's not in front. 

I made my own local fix for this by grabbing the initial widths of all the images on the page on document ready, and then added to the 'updateChild' function as such. Feel free to use this or similar code to fix this issue:

```
        var childImgs = $(child).find('img');

        for (var i = 0; i < pageImgs.length; i++) {

            for (var j = 0; j < childImgs.length; j++) {

                if (pageImgs[i].src === childImgs[j].src) {  // using this to match image to it's original width
                    $(childImgs[j]).css({
                        width: (factors.adjustedScale * pageImgs[i].width).toFixed(1) + "px"
                    });
                }
            }
        }
```

**Comment by fredleblanc** [comment]
The best solution is to set the size of images in em's or %. Font-size will scale, causing those to scale with it. 

– Fred on the go

**Comment by tonye** [comment]
Interesting... I will try that, thanks.
