### ISSUE TITLE
css line-height value screws up font scaling

### ISSUE THREAD

**Issue by tonye** [fredleblanc/roundabout#85]
I had an issue where font size was scaling down when rotating out, but it seemed I was getting more space between lines when an element would rotate out, which pushed content down and outside of the bounds of the shrinked element. 

I discovered the line-height property was set to 1.6em for my <ul> tags across my site, which was part of the ASP.Net MVC initial template.This may not be a bug, but is a weakness in the roundabout script that should be corrected.

**Comment by fredleblanc** [comment]
Yup, em's fix that. 

I consider using em's (or ideally, scale — which is just a number with no unit) for line-height to be a best practice. Roundabout reinforces those beliefs (for good or otherwise).

– Fred on the go

**Comment by tonye** [comment]
Bah ok, apparently the only issue is my lack of experience. I do suggest adding this information to the website's instructions for the plugin. Perhaps an FAQ or Gotcha's section.
